#player_1 = Player.create({name: "table"})
#player_1 = Player.create({name: "trash"})


card_1 = Card.create({name: "copper", cost: 0, kind: "treasure", stock: 60, in_randomizer?: false})
card_2 = Card.create({name: "silver", cost: 3, kind: "treasure", stock: 40, in_randomizer?: false})
card_3 = Card.create({name: "gold", cost: 6, kind: "treasure", stock: 30, in_randomizer?: false})

card_4 = Card.create({name: "estate", cost: 2, kind: "victory", stock: 12, in_randomizer?: false})
card_5 = Card.create({name: "duchy", cost: 5, kind: "victory", stock: 12, in_randomizer?: false})
card_6 = Card.create({name: "provence", cost: 8, kind: "victory", stock: 12, in_randomizer?: false})

card_7 = Card.create({name: "curse", cost: 0, kind: "curse", stock: 30, in_randomizer?: false})

card_8 = Card.create({name: "village", cost: 3, kind: "action", stock: 10, in_randomizer?: true})
card_9 = Card.create({name: "smithy", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_10 = Card.create({name: "market", cost: 5, kind: "action", stock: 10, in_randomizer?: true})
card_11 = Card.create({name: "laboratory", cost: 5, kind: "action", stock: 10, in_randomizer?: true})
card_12 = Card.create({name: "festival", cost: 5, kind: "action", stock: 10, in_randomizer?: true})
card_21 = Card.create({name: "cellar", cost: 2, kind: "action", stock: 10, in_randomizer?: true})
card_13 = Card.create({name: "woodcutter", cost: 3, kind: "action", stock: 10, in_randomizer?: true})
card_14 = Card.create({name: "workshop", cost: 3, kind: "action", stock: 10, in_randomizer?: true})
card_15 = Card.create({name: "throne room", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_16 = Card.create({name: "witch", cost: 5, kind: "action", stock: 10, in_randomizer?: true})
card_17 = Card.create({name: "militia", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_18 = Card.create({name: "spy", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_19 = Card.create({name: "thief", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_20 = Card.create({name: "remodel", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_21 = Card.create({name: "council room", cost: 5, kind: "action", stock: 10, in_randomizer?: true})
card_22 = Card.create({name: "feast", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_23 = Card.create({name: "chapel", cost: 2, kind: "action", stock: 10, in_randomizer?: true})
card_24 = Card.create({name: "bureaucrat", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_25 = Card.create({name: "chancellor", cost: 3, kind: "action", stock: 10, in_randomizer?: true})
card_26 = Card.create({name: "moneylender", cost: 4, kind: "action", stock: 10, in_randomizer?: true})
card_27 = Card.create({name: "mine", cost: 5, kind: "action", stock: 10, in_randomizer?: true})
card_28 = Card.create({name: "library", cost: 5, kind: "action", stock: 10, in_randomizer?: true})
card_29 = Card.create({name: "adventurer", cost: 6, kind: "action", stock: 10, in_randomizer?: true})
card_30 = Card.create({name: "moat", cost: 2, kind: "action", stock: 10, in_randomizer?: true})
card_31 = Card.create({name: "gardens", cost: 4, kind: "victory", stock: 12, in_randomizer?: true})
